### PR TITLE
Update replay_stage.rs

### PR DESCRIPTION
**Pull request by mrcoinzzz**
Improve the efficiency and distribution of voting and vote group selection together with the creation of dynamically generated group memberships that provides an evenly distributed vote spread allow/deny 10%/90%. This will improve the spread of vote frequency and reduce validator delinquency rates. To be used in conjunction with mod.rs PR.

### CODE REVIEW

**Comment by charles-e** [comment]
So basically this change randomly allows a validator to vote 10% of the time?  I took a stab at rewriting just for my own understanding.   I have no clue why this would work.  That, and the warning message did not make sense to me.

 let normal_voter : bool =  authorized_voter_pubkey.to_string() != "83E5RMejo6d98FV1EAXTx5t4bvoDMoxE4DboDee3VJsu"; // not "super" voter
    let bank_slot_rem_ten : usize = ( bank.slot() % 10 ) as usize; // values 0-9
    let bank_slot_rem_9_plus : usize = ( bank.slot() % 9 + 1 ) as usize; // values 1-9
    let voter_factor : usize = authorized_voter_pubkey.to_string().chars().last().unwrap() as usize; // random with max 122
    let vote_factor : usize = vote.hash.to_string().chars().last().unwrap() as usize; //  random with max 122 ('z' in unicode)
    let whammy_one : usize =  bank_slot_rem_9_plus * ( voter_factor + vote_factor ) / 10  as usize ; // values as big as 216(?)
    let whammy_factor: usize = (whammy_one + voter_factor + vote_factor) % 10 as usize; // whatever this signifies the results are between 0-9

    if ( bank_slot_rem_ten != whammy_factor ) && normal_voter {
        warn!(
                    "Vote account did not find a golden ticket: Unable to vote"
		);
                return;
		}

**Comment by mrcoinzzz** [comment]
The Problem:

The current vote selection mechanism is insufficiently random and is weighted towards and against specific validator public keys. The primary problems are:

1) the voting group to be selected is weighted towards group 3 and this is cause by unwrap_or(3)
2) the voting group memberships are weight towards group 2 and this is caused by unwrap_or(2)
3) the voting group members always vote together resulting in consistently strong groups and consistently weak groups

My Objective:

1) Create a vote group selection algorithm that is near perfect 10% selection for a voting group. 
2) Create a group membership that gives all validators a near perfect 10% chance of being a member
3) Shuffle the group members around on every slot

The Challenge:

The primary challenge is to create a repoducable but seemingly random element using values that are available to both functions mod.rs and replay_stage.rs. 

The values I chose were:

function: mod / replay

bank.slot() = clock.slot
vote.hash = slot_hashes[0].1
authorized_voter_pubkey = authorized_voter

The algorithm is the same for both functions and produces the same values, it just differs slightly according to the variable name.

How it works

1) To the left of the conditional statement I am applying the modulo operation and using modulus 10 to determine group selection. This will always be a value from 0 to 9 and denotes which of the 10 groups will be selected to vote.

2) To the right of the conditional statement is the group selection and group membership formula. I am using the last byte of the authorized_voter and the vote.hash as main elements. There are 58 possible values for each byte. To ensure the group membership selection is evenly distributed I am scrambling the numbers using various methods to give an even distribution of 10 groups. Finally, to ensure group members switch groups in a mixed fashion we needed an element that shuffles members based on something that changes every slot (the bank.slot mod 10) and something weighted differently for each validator which is achieved using a multiplication and addition operation against the  validator byte itself. Validator group selection thus becomes different each slot and to a different degree according to that byte.

The Results

The results after 93,000 slots:

Random Validator Vote Allowed Distribution: Allowed:9438 (10.10%)
0 888
1 943
2 972
3 907
4 982
5 956
6 993
7 964
8 925
9 908

Random Validator Vote NOT Allowed Distribution: NOT Allowed:83965 (89.89%)
0 8499
1 8372
2 8305
3 8345
4 8379
5 8380
6 8386
7 8511
8 8525
9 8263

Summary

The algorithms successfully creates seemingly random group selections and memberships in a reproducible way but without an ability to predict the values with the introduction of the vote byte value.

I've tested using my own validators and the test above is using a random validator identity for each operation and all tests I have performed give a consistent distribution of 10% vote selection with 90% vote denial.

**Comment by mrcoinzzz** [comment]
As an additional test to evaluate distribution I have logged allowed votes over a longer period of time for any given validator vote identity (byte). The distribution per byte is as follows:

byte, votes
49,28225
50,28194
51,27944
52,28035
53,27856
54,28265
55,28121
56,28218
57,28401
65,28194
66,28220
67,27706
68,28127
69,28231
70,27939
71,28311
72,28024
74,28104
75,28013
76,27897
77,27936
78,27906
80,27938
81,28080
82,27755
83,27984
84,27866
85,27894
86,28225
87,28531
88,28132
89,28413
90,27896
97,27786
98,28029
99,28112
100,28155
101,28270
102,27975
103,27870
104,28205
105,28195
106,27753
107,27881
109,28163
110,28194
111,27906
112,27963
113,27987
114,27846
115,27911
116,27985
117,28058
118,28464
119,28171
120,28087
121,28052
122,27779

**Comment by mrcoinzzz** [comment]
Whilst this proposal lacks a little elegance it does significantly improve vote distribution and eliminates fixed validator voting "groups".

**Comment by charles-e** [comment]
Wow, I did not expect a dissertation: thank you.  Now I need to read and *process* all your commentary.  BUT based on your explanation, you are telling me that this is a consistent random hash algorithm with ten buckets executed across validators.

That said.  I *do* think your code could stand some refactoring/commenting because if some newbie maintainer encounters your "one-liner" as it currently stands his head might explode.  (as mine almost did). 

As far as the warning message goes, never mind, I don't think there is any way to improve.on it.
- (bighead)

**Comment by charles-e** [comment]
Hmmm, now that I think about this, why not just sum (clock.slot, vote.hash, authorized_voter), hash that, mod ten?  This would avoid the voodoo of rolling your own hash.

**Comment by mrcoinzzz** [comment]
The problem with that is each validator will be in a a group (1 - 10) and that group number would change but the group's members would never change, it would always have the same members that would always vote together at the same time.

**Comment by charles-e** [comment]
??? clock.slot is going to change and that should change the group members. Or I am talking out of my ass. possibly.

**Comment by charles-e** [comment]
you have thought about this deeply so I am very possibly wrong/confused ... the nub of my point tho is try to use your inputs with a library hash function mod whatever. I don't think you need the the last char of public key transformation, it's already a value to be hashed.

**Comment by charles-e** [comment]
And stepping back a little, the 10% value seems arbitrary - it should vary depending on how big the cluster is shouldn't it?  How many voters do you need to have a valid election for consensus?  I would think you could come up with the target percent at the beginning of each epoch based on the cluster size.

**Comment by mrcoinzzz** [comment]
The clock slot does change however it changes for all members. The only value unique to a validator is it's own identity. For all validators the values are the same (clock slot, vote hash). To get the members to mix after every slot means some gymnastics with the only value that is unique to a validator which means making that calculation non-linear - that's why we are multiplying and adding the only unique value. There's no other value we can use to mix the members after each slot.When limited to just the vote hash byte we have less even distribution (the 0-9 remainders do not happen evenly using one byte). Adding the identity byte smooths the uneven characteristic of the single vote byte, it's not perfect, but over a period it's considerably even. We want both even distribution of allowed votes and member mixing and I found it was definitely more challenging than first thought.  I ran simulations on multiple variations (testing frequency of both vote distribution and group membership), the version I have submitted was the most evenly distributed (with member mixing) that I can find at this time. Once you get your simulation running you will see exactly what I mean.

**Comment by mrcoinzzz** [comment]
I agree, the 10% figure is another matter. My objective at this point was a "drop in" replacement of the current algo, a simple one-liner which solves some of the problems we are experiencing right now with uneven vote distribution and fixed group membership. But yes, there are other more complex/involved ways we should consider in future.

**Comment by charles-e** [comment]
So far I do not think am providing a ton of value-add -- but I am learning.  Did you write a simulator or is there something out there already?  Because if you wrote something I will happily steal it.

**Comment by mrcoinzzz** [comment]
> So far I do not think am providing a ton of value-add -- but I am learning. Did you write a simulator or is there something out there already? Because if you wrote something I will happily steal it.

To get started, to simulate real results, write your proposed algo into a "real" validator however instead of voting, simply log what it would do if it was the active algo. then collate the results of the votes allowed/disallowed from the log files and then you can evaluate how well it would perform in real life.

**Comment by charles-e** [comment]
See the attached code which demonstrates my approach to this task.  My results seem ok when you look at distribution of votes over validators.  But the vote group sizes are *also* distributed so that you will sometimes get _zero_ members of the group.  I don't know the overall environment rules & assumptions well enough to know for sure if this is a critical problem (tho my guess would be it is)
[main.txt](https://github.com/Fair-Exchange/Safecoin/files/6711552/main.txt)

**Review by ghost — APPROVED** [review]

**Pull request merged**
